package it.polimi.ingsw.client.states;

public enum stateEnum {
    LOGIN,
    LOGIN_SUCCESSFUL,
    LOGIN_FAILED,
    WAITING_LOBBY,
    SELECT_NUM_PLAYERS,
    LOBBY,
    SELECT_TOKEN,
    WAITING_TURN,
    PLAY_CARD,
    DRAW_CARD,
    DISCONNECTION,
    ALREADY_STARTED,
    REJECTED,
    SHOW_CARDS,
    SHOW_PLAYER_RESOURCES,
    SHOW_PLAYER_BOARD,
    DRAW_CARD_RESPONSE
}
